distribution_code_name: Squirrel
distribution_name: "鼠鬚管"
distribution_version: 0.14.0
install_time: "Mon Dec 16 09:42:04 2019"
installation_id: "cf1ccdc0-5b6f-4c8a-b641-1bf0d833728c"
rime_version: 1.5.3