# 適用於【鼠鬚管】0.9.13+
# 位置：~/Library/Rime/squirrel.custom.yaml
# 用法：想要哪項生效，就刪去該行行首的#字符，但注意保留用於縮進的空格

patch:
#  us_keyboard_layout: true      # 鍵盤選項：應用美式鍵盤佈局
#  show_notifications_when: growl_is_running  # 狀態通知，默認裝有Growl時顯示，也可設爲全開（always）全關（never）
#  style/horizontal: true        # 候選窗横向顯示
#  style/inline_preedit: false   # 非內嵌編碼行
#  style/font_face: "儷黑 Pro"    # 我喜歡的字體名稱
#  style/font_point: 18          # 字號
#  style/corner_radius: 10       # 窗口圓角半徑
#  style/border_height: 0        # 窗口邊界高度，大於圓角半徑才有效果
#  style/border_width: 0         # 窗口邊界寬度，大於圓角半徑才有效果
#  style/color_scheme: clean_white      # 選擇配色方案

  style/color_scheme: system_purple            # 方案命名，不能有空格
  preset_color_schemes:
    system_purple:
      author: "scomper <scomper@gmail.com>"    # 作者信息
      back_color: 0xFFFFFF                     # 候选条背景色，24位色值，16进制，BGR顺序
      border_color: 0xE0B693                   # 边框色
      candidate_text_color: 0x000000           # 预选项文字颜色
      comment_text_color: 0x999999             # 拼音等提示文字颜色
      hilited_back_color: 0xFFF8F8             # 第一候选项背景背景色
      hilited_candidate_text_color: 0xA456A2   # 第一候选项文字颜色
      hilited_candidate_label_color: 0xA456A2  # 第一候选项编号颜色
      hilited_comment_text_color: 0x999999     # 注解文字高亮
      hilited_text_color: 0x999999             # 高亮拼音 (需要开启内嵌编码)
      name: "系统紫／System Purple"
      text_color: 0x424242                     # 拼音行文字颜色
      label_color: 0x999999                    # 预选栏编号颜色

      horizontal: true                         # 水平排列
      inline_preedit: true                     # 单行显示，false双行显示
      candidate_format: "%c\u2005%@\u2005"     # 用 1/6 em 空格 U+2005 来控制编号 %c 和候选词 %@ 前后的空间。
      font_point: 15                           # 候选文字大小
      label_font_point: 13                     # 候选编号大小
      label_font_face: "SFCompactText-Regular" # 候选词编号字体
      corner_radius: 6                         # 候选条圆角
      hilited_corner_radius: 6                 # 高亮圆角
      border_height: 6                         # 窗口边界高度，大于圆角半径才生效
      border_width: 6                          # 窗口边界宽度，大于圆角半径才生效
      border_color_width: 0

  "app_options/com.runningwithcrayons.Alfred-3/ascii_mode": true

# 註：預設的配色方案及代碼（指定爲 style/color_scheme ）
#   系統默認色系 - native
#   碧水 - aqua
#   青天 - azure
#   明月 - luna
#   墨池 - ink
#   孤寺 - lost_temple
#   暗堂 - dark_temple
#   星際我爭霸 - starcraft
#   谷歌 - google
#   曬經石 - solarized_rock
#   简约白 - clean_white